name: CI/CD Migration
on:
  push:
    branches:
      - develop
      - test
      - main
    paths:
      - sql/**
  pull_request:
    branches:
      - develop
      - test
      - main
    types: [closed]
    paths:
      - sql/**
  workflow_dispatch:

jobs:
  build:
    name: üêò Build Migration Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set docker tags
        id: meta
        run: |
          IMAGE=hungnn2810/lifebalance-backend
          BRANCH=${GITHUB_REF_NAME}
          SHA=${GITHUB_SHA}
          
          if [ "$BRANCH" = "main" ]; then
            LATEST_TAG="$IMAGE:migration-latest"
          else
            LATEST_TAG="$IMAGE:migration-latest-$BRANCH"
          fi
          
          echo "tags<<EOF" >> $GITHUB_OUTPUT
          echo "$IMAGE:migration-$SHA-$BRANCH" >> $GITHUB_OUTPUT
          echo "$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build & push migration image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile-migration
          push: true
          tags: ${{ steps.meta.outputs.tags }}